### ISSUE TITLE
D3D12 WARNING crashes graphics debugging

### ISSUE THREAD

**Issue by cpyburn** [Microsoft/DirectX-Graphics-Samples#158] opened 2016-05-17 21:56 UTC
```
D3D12 WARNING: ID3D12Resource::ID3D12Resource::Map: pReadRange is NULL and the heap page property is WRITE_BACK. This can be an indicator of inefficiencies that will result on mobile systems, as the range should be as tight as possible. But, it is also possible the range must encompass the whole subresource.A NULL pReadRange parameter indicates all resource memory will be read by the CPU.  [ EXECUTION WARNING #930: MAP_INVALID_NULLRANGE]

D3D12 WARNING: ID3D12Resource::ID3D12Resource::Unmap: pWrittenRange is NULL and the heap page property is WRITE_BACK. This can be an indicator of inefficiencies that will result on mobile systems, as the range should be as tight as possible. But, it is also possible the range must encompass the whole subresource.A NULL pWrittenRange parameter indicates all resource memory was written to.  [ EXECUTION WARNING #931: UNMAP_INVALID_NULLRANGE]
```
I am trying to execute two command lists at once to see if gpu cores, and heaps are being used properly and I can't debug it because this pops up and crashes the debugger.  When I execute without graphics debugger everything works perfectly, both command lists are rendering their draw commands and everything looks fine.
![untitled](https://cloud.githubusercontent.com/assets/17934438/15340830/656ef57e-1c40-11e6-9f86-d1b30bd54c23.png)

**Comment by walbourn** [comment] 2016-05-18 00:28
It's a performance warning. You can ignore it, but you probably shouldn't.

**Comment by cpyburn** [comment] 2016-05-18 01:59
I'm not unmapping anything. This is a bug. I recieve no warnings from compiling or running, only when going to the graphics debugger. Which is probably itself mapping or unmapping and causing itself to crash

**Comment by cpyburn** [comment] 2016-05-18 13:53
Here is the code if it helps

```
ID3D12DescriptorHeap* ppHeaps[] = { m_heap.Get() };
	D3D12_VIEWPORT viewport = m_deviceResources->GetScreenViewport();

	//------------------------------------------------------------------------------------------------------------------
	DX::ThrowIfFailed(m_deviceResources->GetCommandAllocator()->Reset());
	DX::ThrowIfFailed(m_commandList->Reset(m_deviceResources->GetCommandAllocator(), nullptr));
	m_commandList->SetDescriptorHeaps(_countof(ppHeaps), ppHeaps);
	m_commandList->RSSetViewports(1, &viewport);
	m_commandList->RSSetScissorRects(1, &m_scissorRect);

	CD3DX12_RESOURCE_BARRIER renderTargetResourceBarrier =
		CD3DX12_RESOURCE_BARRIER::Transition(m_deviceResources->GetRenderTarget(), D3D12_RESOURCE_STATE_PRESENT, D3D12_RESOURCE_STATE_RENDER_TARGET);
	m_commandList->ResourceBarrier(1, &renderTargetResourceBarrier);

	D3D12_CPU_DESCRIPTOR_HANDLE renderTargetView = m_deviceResources->GetRenderTargetView();
	D3D12_CPU_DESCRIPTOR_HANDLE depthStencilView = m_deviceResources->GetDepthStencilView();
	m_commandList->ClearRenderTargetView(renderTargetView, DirectX::Colors::CornflowerBlue, 0, nullptr);
	m_commandList->ClearDepthStencilView(depthStencilView, D3D12_CLEAR_FLAG_DEPTH, 1.0f, 0, 0, nullptr);

	m_commandList->OMSetRenderTargets(1, &renderTargetView, false, &depthStencilView);

	//------------------------------------------------------------------------------------------------------------------
	m_terrain.RenderTerrainCells(m_commandList, m_heap);

	m_textRenderer.Begin(m_commandList, m_heap, false);
	m_textRenderer.EnableDropShadow(m_commandList, false);
	m_textRenderer.SetColor(XMFLOAT4(1.0f, 1.0f, 1.0f, 1.0f));
	m_textRenderer.SetTextSize(20.0f);
	m_textRenderer.DrawString(m_commandList, "Yaw:" + to_string(m_camera->Yaw()) + "D:" + to_string(m_camera->Yaw() * 180 / XM_PI));
	m_textRenderer.NewLine();
	m_textRenderer.DrawString(m_commandList, "Pitch:" + to_string(m_camera->Pitch()) + "D:" + to_string(m_camera->Pitch() * 180 / XM_PI));
	m_textRenderer.NewLine();
	m_textRenderer.DrawString(m_commandList, "Look At:" + to_string(m_camera->LookAt().x) + ":" + to_string(m_camera->LookAt().y) + ":" + to_string(m_camera->LookAt().z));
	m_textRenderer.NewLine();
	m_textRenderer.DrawString(m_commandList, "Velocity:" + to_string(m_controller->Velocity().x) + ":" + to_string(m_controller->Velocity().y) + ":" + to_string(m_controller->Velocity().z));
	m_textRenderer.End(m_commandList);
	//------------------------------------------------------------------------------------------------------------------

	DX::ThrowIfFailed(m_commandList->Close());



	DX::ThrowIfFailed(m_commandListTest->Reset(m_deviceResources->GetCommandAllocator(), nullptr));
	m_commandListTest->SetDescriptorHeaps(_countof(ppHeaps), ppHeaps);
	m_commandListTest->RSSetViewports(1, &viewport);
	m_commandListTest->RSSetScissorRects(1, &m_scissorRect);

	m_commandListTest->OMSetRenderTargets(1, &renderTargetView, false, &depthStencilView);

	// draw the model
	m_model.RenderDirectX(m_commandListTest, m_heap);

	CD3DX12_RESOURCE_BARRIER presentResourceBarrier =
		CD3DX12_RESOURCE_BARRIER::Transition(m_deviceResources->GetRenderTarget(), D3D12_RESOURCE_STATE_RENDER_TARGET, D3D12_RESOURCE_STATE_PRESENT);
	m_commandListTest->ResourceBarrier(1, &presentResourceBarrier);

	DX::ThrowIfFailed(m_commandListTest->Close());

	ID3D12CommandList* ppCommandLists[] = { m_commandList.Get(), m_commandListTest.Get() };
	m_deviceResources->GetCommandQueue()->ExecuteCommandLists(_countof(ppCommandLists), ppCommandLists);
```

**Comment by bobbrow** [comment] 2016-05-18 15:46
Thanks for the report.  This is an issue we're aware of.  Can I safely assume you're using build 10586?  From what I recall, these warnings were added after the initial release of Windows 10 (build 10240) and the graphics debugger wasn't fixed up to deal with them in time.

Two things you can try to work around the issue:
  1. Open the Visual Studio Options dialog, and go to Graphics Diagnositcs -> Capture.  Disable "Stop capture if any SDK layers errors are found"
  2. If that doesn't work, try commenting out the code that loads the SDK layers while in the DEBUG config, or switch to RELEASE while doing graphics debugging.  If you are using the DirectX control panel (dxcpl.exe) to force the SDK layers on, you will need to disable that.

**Comment by cpyburn** [comment] 2016-05-18 17:44
Thanks bobbrow and yes 10.0.10586.0. If you are aware of the issue you can close this.  Any idea when the fix is coming out?  And I will try your work around.

**Comment by bobbrow** [comment] 2016-05-18 22:12
I don't have a timeline for the fix right now.  What I am interested to know is whether or not the graphics debugger still crashes for you even with the SDK layers disabled.  I would not expect this warning to crash the graphics debugger, so if it continues to crash, we may need some additional information.

**Comment by cpyburn** [comment] 2016-05-19 01:18
work around 1 did not work.  Could you elaborate on number 2 commenting out the code that loads the SDK?

**Comment by bobbrow** [comment] 2016-05-19 15:31
Yeah.  Comment out this section or just the ```EnableDebugLayer``` line:
```
	// Enable the D3D12 debug layer.
	{
		ComPtr<ID3D12Debug> debugController;
		if (SUCCEEDED(D3D12GetDebugInterface(IID_PPV_ARGS(&debugController))))
		{
			debugController->EnableDebugLayer();
		}
	}
```

**Comment by cpyburn** [comment] 2016-05-19 22:36
Yes it still crashes, although now it gives 
`Exception thrown at 0x75FFDAE8 in App1.exe: Microsoft C++ exception: _com_error at memory location 0x039B9360.
The thread 0x33cc has exited with code 0 (0x0).
Exception thrown at 0x75FFDAE8 in App1.exe: Microsoft C++ exception: _com_error at memory location 0x039B9360.
The thread 0x2d68 has exited with code 0 (0x0).
Exception thrown at 0x75FFDAE8 in App1.exe: Microsoft C++ exception: _com_error at memory location 0x039B9360.
The thread 0x2510 has exited with code 0 (0x0).
Exception thrown at 0x75FFDAE8 in App1.exe: Microsoft C++ exception: _com_error at memory location 0x039B9360.
The thread 0x2e14 has exited with code 0 (0x0).
Exception thrown at 0x75FFDAE8 in App1.exe: Microsoft C++ exception: _com_error at memory location 0x039B9360.
The thread 0x210 has exited with code 0 (0x0).
Exception thrown at 0x75FFDAE8 in App1.exe: Microsoft C++ exception: _com_error at memory location 0x039B9360.
The thread 0x1b20 has exited with code 0 (0x0).`

**Comment by bobbrow** [comment] 2016-05-19 23:27
Ok, that's what I suspected. From your original post, it looks like the crash happens when you're loading the frame captures into the playback engine. If you're willing to share the .vsglog or some source code with us, we can take a deeper look to try to find the source of the crash.

**Comment by cpyburn** [comment] 2016-05-20 14:19
I am willing to share.  Attached is report vsglog and let me know what you need from the source
[Report20160520-0714.vsglog_131082272528672054.cache.zip](https://github.com/Microsoft/DirectX-Graphics-Samples/files/274745/Report20160520-0714.vsglog_131082272528672054.cache.zip)

**Comment by bobbrow** [comment] 2016-05-20 18:17
Thanks!  I took a quick look and I see a crash in the nVidia driver when SetDescriptorHeaps is called on your command list with a CBV/SRV/UAV Descriptor heap containing 1004 descriptors.  Does that sound right?  Unfortunately, I don't have a workaround for you, but I will pass this on to the debugger team.

**Comment by cpyburn** [comment] 2016-05-20 19:00
Yes that is correct, thanks a ton.

**Comment by bobbrow** [comment] 2016-05-20 19:57
Digging a little more, it looks like only 9 of the 1004 descriptors are initialized.  I suspect that maybe the debugger is capturing uninitialized descriptors and trying to restore them during playback which results in a driver crash.  Can you try shrinking your descriptor heap down to 9 entries and see if the debugger is able to capture and replay your scene?

**Comment by cpyburn** [comment] 2016-05-20 20:52
Yeah those were just place holders for testing, I shrunk to 9 and still crashes.  Here is the vsglog
[Report20160520-1349.vsglog_131082509948392910.cache.zip](https://github.com/Microsoft/DirectX-Graphics-Samples/files/275425/Report20160520-1349.vsglog_131082509948392910.cache.zip)

**Comment by bobbrow** [comment] 2016-05-24 18:09
Good to see that you found a workaround.  On my side, I tried a preview of the next Windows Insider build and I was able to load the capture without issue, so it appears that this bug has already been found and fixed by the graphics debugger team and will be present in the next Insider build.

**Comment by cpyburn** [comment] 2016-05-24 19:25
My main development machine is NVidia, so unfortunately, not really a work around.  Its just good to see the code working.  I went ahead and wrote a helper class that uses 1 command list, and 1 heap for development on my machine.  Once the debugger is working (next release), I will convert it over to use multiple command lists and multiple heaps.  It is good to know that the fix is on the way!  Thanks for your help.  You can close the issue if the fix will be in the next release.

**Comment by bobbrow** [comment] 2016-06-10 21:12
I just confirmed that I can playback this capture with the Windows Insider Fast build that came out this week (14361).  I will close the issue.

**Closed by bobbrow** 2016-06-10 21:12 UTC

**Comment by bobbrow** [comment] 2016-07-06 19:12
intc
