### ISSUE TITLE
D3D12ExecuteIndirect: D3D12 ERROR: ID3D12CommandAllocator::Reset

### ISSUE THREAD

**Issue by BasilThePlant** [Microsoft/DirectX-Graphics-Samples#196] opened 2016-09-04 21:57 UTC
Hi I'm getting this error when I try running D3D12ExecuteIndirect.  This is also happening for my own application that uses ExecuteIndirect although I don't know if that is the issue.  

Thanks

D3D12 ERROR: ID3D12CommandAllocator::Reset: A command allocator is being reset before previous executions associated with the allocator have completed. [ EXECUTION ERROR #552: COMMAND_ALLOCATOR_SYNC]
The thread 0x2350 has exited with code 0 (0x0).
The thread 0x1560 has exited with code 0 (0x0).
D3D12 ERROR: ID3D12CommandAllocator::Reset: A command allocator is being reset before previous executions associated with the allocator have completed. [ EXECUTION ERROR #552: COMMAND_ALLOCATOR_SYNC]
The thread 0x2dcc has exited with code 0 (0x0).
The thread 0xcd8 has exited with code 0 (0x0).
D3D12 ERROR: ID3D12CommandAllocator::Reset: A command allocator is being reset before previous executions associated with the allocator have completed. [ EXECUTION ERROR #552: COMMAND_ALLOCATOR_SYNC]
The thread 0x1598 has exited with code 0 (0x0).
The thread 0x2270 has exited with code 0 (0x0).
D3D12 ERROR: ID3D12CommandAllocator::Reset: A command allocator is being reset before previous executions associated with the allocator have completed. [ EXECUTION ERROR #552: COMMAND_ALLOCATOR_SYNC]
The thread 0x4e0 has exited with code 0 (0x0).
The thread 0x2464 has exited with code 0 (0x0).
D3D12 ERROR: ID3D12CommandAllocator::Reset: A command allocator is being reset before previous executions associated with the allocator have completed. [ EXECUTION ERROR #552: COMMAND_ALLOCATOR_SYNC]
The thread 0x26f8 has exited with code 0 (0x0).
The thread 0x1dd8 has exited with code 0 (0x0).
D3D12 ERROR: ID3D12CommandAllocator::Reset: A command allocator is being reset before previous executions associated with the allocator have completed. [ EXECUTION ERROR #552: COMMAND_ALLOCATOR_SYNC]

**Comment by bobbrow** [comment] 2016-09-06 23:15
Is this also on your fast ring OS (similar to Issue #195)?  I don't see this on the Anniversary Update.

**Comment by BasilThePlant** [comment] 2016-09-09 18:14
Apologies for the late reply: yes!

**Comment by bobbrow** [comment] 2016-09-21 22:09
I picked up the latest Insider Fast build and tried the sample on both AMD and NVidia.  I still don't see this debug message.  Do you know if this is running on your Intel GPU or the discrete GPU?  I might have to go track down a laptop.

**Comment by BasilThePlant** [comment] 2016-09-21 22:31
Hi Bob, currently happening on my Nvidia 860M, not my Intel GPU and my insider build is now 14926.rs_prerelease.160910-1529.  So you might have to find a laptop to reproduce it. :( 
Thanks

**Comment by bobbrow** [comment] 2016-09-21 22:36
It's possible that this is a bug in DXGI.  I saw something similar back in the TH2 timeframe when I was working on some issues related to hybrid laptops.  I suspect that this is not the sample's Command Allocator.  If that is the case, then perhaps any laptop will do.

**Comment by bobbrow** [comment] 2016-09-22 23:08
I found a laptop and I have a repro.  We'll look into this.

**Comment by bobbrow** [comment] 2016-09-23 19:48
This looks like an issue in the SDK layers that was very recently identified and fixed.  It should be available in a future Insider build though I can't say how soon at this point.

**Comment by BasilThePlant** [comment] 2016-09-23 22:36
Excellent stuff Bob. Thank you ever so much for taking the time to investigate and fix this for me. If you could post back a build no. that contains the fix when you know it, that would be much appreciated. Thanks

**Comment by bobbrow** [comment] 2016-10-25 19:08
I have confirmed the fix is in build 14951.

**Closed by bobbrow** 2016-10-25 19:08 UTC
