### ISSUE TITLE
CMake-ify the d3d12 helper library - FetchContent

### ISSUE THREAD

**Issue by ghost** [microsoft/DirectX-Graphics-Samples#616] opened 2020-02-20 18:55 UTC
I've created a fork to help illustrate this point: 
https://github.com/YMba9g8j9CJp0wLoQf5y/Unofficial-D3D12-Helper-Library

Isolate the d3d12 helper library from the rest of the DirectX-Graphics-Samples. And allow usage of cmake's FetchContent module.

I think allowing this helps with a lot of modern cmake workflows and facilitates easier usage of the helper library. Helping users receive updates (bug fixes, new functions, etc.) and making contributions.

**Comment by jeremyong** [comment] 2020-07-26 23:06
FWIW I just encountered this issue because I was seeing if there was interest in cmake-ifying this entire repository.

Visual Studio... doesn't work. I find it needs to be reinstalled frequently due to either installation corruption or some other issue. Currently I'm running into "cannot open source file cctype.h" indicating Visual Studio can't even find a valid libc to link to.

**Comment by walbourn** [comment] 2020-07-27 18:56
The general distribution model for the ``D3DX12.H`` helper library is to copy it into any project that uses it. A copy of it is included i various Visual Studio project templates--including my own [directx-vs-templates](https://github.com/walbourn/directx-vs-templates).

Another issue is that generally the D3DX12.H helper library here requires the latest Windows 10 SDK to build. Older versions work with older Windows 10 SDKs.

**Comment by walbourn** [comment] 2020-07-27 19:07
Note that the functionality you are using requires CMake 3.14, although you have marked it as requiring CMake 3.16.

For the version of CMake that comes with Visual Studio, that requires VS 2019 16.1 (3.14) or VS 2019 (16.5) (3.16).

**Comment by YMba9g8j9CJp0wLoQf5y** [comment] 2020-08-19 17:55
**"The general distribution model for the D3DX12.H helper library is to copy it into any project that uses it. A copy of it is included i various Visual Studio project templates--including my own directx-vs-templates."**

Copying code into projects is error prone. I've had it happen helping developers on their projects.

Here is an example of a project using fetch content instead:
```
include_guard()

include(FetchContent)

# Helper function to download the dx12 helper library
function(SetupDx12)    
    FetchContent_Declare(d3dx12
        # Unofficial github I maintain
        GIT_REPOSITORY "https://github.com/hdf89shfdfs/D3DX12"
        # Version 2.0 adds OS error checking
        GIT_TAG "2.0"
        # I don't need the history
        GIT_SHALLOW ON
    )

    FetchContent_MakeAvailable(d3dx12)
endfunction()
```

Using git tags instead makes everything super clear.

**"Another issue is that generally the D3DX12.H helper library here requires the latest Windows 10 SDK to build. Older versions work with older Windows 10 SDKs."**

Cmake can detect the SDK and pick the appropriate D3DX12.H header file.
Or perhaps use a compile definition to compile out the code depending on the SDK.
Either one would work.

**"The D3DX12.H helper is also by design header/inline only so it doesn't have any link library or DLL."**

That's fine it can just be an interface library.

```
add_library(d3dx12 INTERFACE)
add_library(Microsoft::D3DX12 ALIAS d3dx12)
```

**"Note that the functionality you are using requires CMake 3.14, although you have marked it as requiring CMake 3.16."**

I just picked what my project was using. The cmake minimum isn't set in stone.

**Comment by walbourn** [comment] 2021-09-10 20:25
Note that the [DirectX-Headers](https://github.com/microsoft/DirectX-Headers/tree/main/include/directx) GitHub repo now has the master copy of ``d3dx12.h``. This is also available on [vcpkg](https://vcpkg.io/) as ``directx-headers``.

**Closed** 2021-09-20 19:31 UTC
Labels: enhancement
