### ISSUE TITLE
D3D12Multithreading has a D3D12 ERROR

### ISSUE THREAD

**Issue by kretash** [Microsoft/DirectX-Graphics-Samples#76] opened 2016-01-01 09:07 UTC
I started to get this error in D3D12Multithreading the sample every time the index buffer is binded.

D3D12 ERROR: ID3D12CommandList::IASetIndexBuffer: pDesc->BufferLocation + SizeInBytes - 1 (0x000000020514a4cb) exceeds end of the virtual address range of Resource (0x0000000000000000, Debug Name: '(nullptr)', GPU VA Range: 0x0000000204e5d000 - 0x0000000204e6cfff). This is OK as out of bounds access is guarded by the GPU (writes are discarded and reads return 0). However the developer probably did not intend to make use of this behavior.  [ STATE_CREATION ERROR #725: SET_INDEX_BUFFER_INVALID]

I wasn't having any error messages with this sample before and I have not modified it. I'm using version 361.43 of nvidias driver.

Thanks.

**Comment by bobbrow** [comment] 2016-01-04 21:20
Can you run ```dxcap -info``` on a CMD prompt and tell me which version of the graphics debugging tools you have?  There are a lot of sections of output that look the same; please paste the section containing binary versions under the heading "System32 Info".  This will help me find a version of the SDK layers that matches yours since the version I have right now does not report this error.

Thanks!

**Comment by kretash** [comment] 2016-01-05 18:10
Here it is

System32 Info
=============
d3d11_3sdklayers.dll            : 10.0.10240.16384 (07/10/15 4:40 AM) 1,427 KB
d3d10warp.dll                   : 10.0.10240.16384 (07/10/15 12:00 PM) 2,484 KB
d3d12warp.dll                   : 10.0.10240.16384 (07/10/15 4:18 AM) 3,182 KB
d3dcompiler_47.dll              : 10.0.10240.16384 (07/10/15 12:00 PM) 4,350 KB
DxCap.exe                       : 10.0.10240.16384 (07/10/15 4:18 AM) 857 KB
DxCaptureReplay.dll             : 10.0.10240.16384 (07/10/15 4:38 AM) 8,052 KB
DxToolsMonitor.dll              : 10.0.10240.16384 (07/10/15 4:17 AM) 169 KB
DxToolsOfflineAnalysis.dll      : 10.0.10240.16384 (07/10/15 4:18 AM) 1,045 KB
DxToolsReportGenerator.dll      : 10.0.10240.16384 (07/10/15 5:36 AM) 95 KB
DxToolsReporting.dll            : 10.0.10240.16384 (07/10/15 4:17 AM) 156 KB
perf_gputiming.dll              : 10.0.10240.16384 (07/10/15 4:28 AM) 301 KB
VsGraphicsCapture.dll           : 10.0.10240.16384 (07/10/15 4:17 AM) 154 KB
VsGraphicsExperiment.dll        : 10.0.10240.16384 (07/10/15 4:17 AM) 1,175 KB
VsGraphicsHelper.dll            : 14.0.23107.0 (07/07/15 8:18 AM) 3,118 KB
VsGraphicsProxyStub.dll         : 10.0.10240.16384 (07/10/15 4:17 AM) 82 KB
VsGraphicsRemoteEngine.exe      : 10.0.10240.16384 (07/10/15 4:21 AM) 4,547 KB

**Comment by bobbrow** [comment] 2016-01-05 21:56
ok, I see you're on Windows 10 RTM then.  I was thinking you were on build 10586.  I'll need to put together a machine with RTM on it, but since I don't see this in build 10586 I suspect that it was a bug in the SDK Layers which has been fixed since then.

**Comment by bobbrow** [comment] 2016-01-05 22:53
I got a repro. I didn't think it was possible for this to be driver-related based on the code I was looking at, but I was able to repro on 10586 after installing 361.43.  It causes the SDK layers to validate the range against the wrong resource.  I haven't root caused it yet though.

**Comment by bobbrow** [comment] 2016-01-09 01:07
We have a suspicion as to the cause and have sent a bug report to NVidia to investigate further.

**Comment by kretash** [comment] 2016-01-09 07:56
Thanks for looking into it :+1:

**Comment by bobbrow** [comment] 2016-01-22 18:57
After discussion with NVidia, we have concluded that the driver is not violating the spec and we will be making a fix to the SDK layer to deal with this case.  Stay tuned...

**Comment by kretash** [comment] 2016-01-29 12:43
Ok, thank you for your help.

**Comment by bobbrow** [comment] 2016-03-04 22:22
We pushed out a fix for this in KB3140743 that went live March 1st.  If you already have the Graphics Tools Optional Feature installed, it will be updated when you install that KB.

**Closed by bobbrow** 2016-03-04 22:22 UTC
