### ISSUE TITLE
nvwgf2umx.dll throws unhandle exception

### ISSUE THREAD

**Issue by worl44** [microsoft/DirectX-Graphics-Samples#515] opened 2018-12-06 15:06 UTC
Hi, i try to build the Helloworld examples but every time i got the same failure:

in D3D12HelloTriangle line 270    ThrowIfFailed(m_swapChain->Present(1, 0));

Exception at 0x00007FFA690BC9A8 (nvwgf2umx.dll) in D3D12HelloTriangle.exe: 0xC000041D: 

I use Visual Studio Community 2017 on Windows 10 Version 1803 (Build 17134.407) with Nvidia Geforce GT 620M with 1 GB
I already try sfc /scannow no issues was found, also i installed the latest Nvidia Driver for my graphics card

**Comment by nyartry** [comment] 2019-01-03 16:24
Hello,

Perhaps, I think that the driver is the cause.

The same phenomenon occurs in GeForce GT 720M environment.
GeForce GT 720M (Driver 3.9135) It is the final driver. (It became out of support.)
It may be impossible to run because it can not satisfy version 4.15.

Probably GeForce GT 620M (driver 3.9135) I think that it is the final driver.

Requirement of DirectX-Graphics-Samples (Nvidia: driver version 415 or higher.)
https://github.com/Microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12Raytracing/readme.md

driver version 4.15
https://us.download.nvidia.com/Windows/416.16/416.16-win10-win8-win7-desktop-release-notes.pdf

driver version 3.91
https://us.download.nvidia.com/Windows/391.35/391.35-win10-win8-win7-desktop-release-notes.pdf

Geforce GT 620 M (DirectX 11.2)
https://www.nvidia.co.jp/object/geforce-gt-620m-jp.html#pdpContent=2

DirectX 12 Support Products
https://www.nvidia.com/en-us/geforce/technologies/dx12/
(candidacy : GeForce GT 720 M)
(demotion : GeForce GT 620 M)

As far as the above is concerned, the GeForce GT 620M may not be able to install 4.15 drivers and may not meet the requirements.



Because the compatible versions may be different for each mother board, we do not know the version of the latest driver of GeForce GT 620M.
Please check the driver version under your circumstances.


Perhaps if GeForce products do not correspond to driver version 4.15, we expect to be truncated from DirectX 12 support.

Because the number has increased too much.


And I gave up.

I think that older products with differences in specifications for each motherboard will continue to have such problems in the future, so I think that even if it can be done, it will be in vain.

Perhaps there are differences in specifications depending on hardware to lower costs?

Recently, it may be devised to prevent such complicated problems from occurring?

So let's buy GeForce RTX.
That is the opinion with the most votes.


If there is a product that can not be handled, nvidia wants us to say clearly.
Since there is a possibility that developers have to investigate.

**Closed** 2019-10-23 17:57 UTC
