### ISSUE TITLE
Win32 vs UWP

### ISSUE THREAD

**Issue by chadmv** [Microsoft/DirectX-Graphics-Samples#7] opened 2015-08-05 18:25 UTC
I wasn't sure where else to ask this so feel free to remove if this isn't the appropriate place.  I noticed the samples are all using Win32 instead of the new UWP API's.  Is that the recommended approach of making DX12 applications?  Or was it just an arbitrary decision for the samples?

**Comment by bobbrow** [comment] 2015-08-05 18:51
Choosing Win32 over UWP for these samples should not be interpreted as a recommendation for all developers.  DX12 is supported in both application platforms and you will find that there is a DX12 UWP project template included with Visual Studio 2015.

As we were developing the samples, we had customers/game studios in our early access program tied to earlier versions of Visual Studio due to requirements of the platforms they develop for.  So we went for the lowest common denominator that would work across multiple development environments (Win32).  We also wanted the samples to focus on the API rather than the application platform plumbing, which is why you will see very minimal Win32 code and window message handling in the majority of these samples.

**Comment by chadmv** [comment] 2015-08-05 19:10
Makes sense.  Thanks for the explanation.

**Comment by weltkante** [comment] 2015-08-29 21:36
@bobbrow The VS 2015 DX 12 template for UWP apps is only using a CoreWindow. We really need a sample/template which sets up DX12 in a "normal" UWP XAML app so we can use XAML UI with DX12, like we already can with DX11.

You say DX12 is supported for UWP, does that include SwapChainPanel? There is no template for DX12+UWP+XAML and I tried to get it working starting from the DX12 CoreWindow template, but CreateSwapChainForComposition is throwing a cryptic exception. I've tried DX11on12, which works for D2D but CreateSwapChainForComposition still fails. Might by my mistake, but proper examples/templates would really help out setting up a basic app which combines DX12 with XAML UI.

Oh, and if this isn't a supported combination it really should be mentioned somewhere in the docs.

**Comment by weltkante** [comment] 2015-09-01 08:36
I wonder if it would make sense to add the DX12 template shipped with VS2015 to this repository, so it can take part in the other refactorings/cleanups/updates taking place here.

In this case I could also imagine spending some time on preparing a pull request for a DX12+SwapChainPanel version of that sample, since I already did the most of the work figuring out how the templates differ.

**Comment by bobbrow** [comment] 2015-09-01 15:18
I think that's a good idea.  I'll float it around and see what the team thinks.

I was going to post something yesterday regarding your previous comment, but was vetting the response with some of my peers.  In short, I had previously prepared the DX12+XAML template for release with Visual Studio 2015, but there was an issue with recovering from device removed errors.  There is some non-determinism in the way that the swap chain is released from the XAML framework which results in a crash while attempting to recover.

The team is aware of the issue and is investigating how it might be fixed, but the fix would not be available in time for the Visual Studio 2015 and Windows 10 releases, so we pulled the template.

You are free to continue developing DX12+XAML, but we will not be providing a template for it until the issue is resolved.  Just be aware that your app will likely crash if the device is removed for any reason.

BTW, either of the FLIP swap effects should be functional with CreateSwapChainForComposition.  I still have my DX12+XAML template and verified this yesterday.

**Comment by weltkante** [comment] 2015-09-01 17:03
Ah, thanks for that information, in particular about the possible crash. I guess that is a valid reason to hold back on it for now; but in the long run it's a much wanted combination of features, I believe, because with the introduction of UWP, the performance of DX12 combined with the power of XAML UI are something which is very useful. (I'm so tired of having to roll custom UI frameworks on top of DirectX ;-) I guess I could use DX11 most of the time, but it feels like having to hold back when you know what DX12 can do ...

I might have missed testing the FLIP_DISCARD + SCALING_STRETCH combination, you are right, that one does work too.

**Comment by HppZ** [comment] 2016-01-09 13:34
DirectX for desktop and for universal app really confused me, what's the difference?

**Comment by weltkante** [comment] 2016-01-09 16:36
If you want to run your DirectX application on phones and other devices you need to create UWP applications which do not have access to the full desktop API. The main difference in DirectX is how you host it, i.e. how you create a window and swap chain. In the actual rendering there isn't much of a difference.

**Comment by HppZ** [comment] 2016-01-10 02:00
Really thanks！

**Comment by bobbrow** [comment] 2016-02-05 18:35
Now that I just committed UWP versions of samples to the repo, I'm going to close this question.

**Closed by bobbrow** 2016-02-05 18:35 UTC
Labels: question

**Comment by HppZ** [comment] 2016-02-18 05:07
I am planning to buy this book "Introduction to 3D Game Programming with DirectX 12", any other great tutorial for beginners online, please?

**Comment by bobbrow** [comment] 2016-02-18 17:40
Please start a new topic. I can give you a response there.  This one is unrelated to your question and makes it harder to search for if someone else has a similar question.

**Comment by HppZ** [comment] 2016-02-19 12:16
OK, thanks.

**Comment by thecobblersfather** [comment] 2016-04-07 17:22
Has there been any update on the DX12+XAML for UWP template? I am currently developing a C#/C++ Direct2D application and have run into an issue creating my SwapChainPanel.

**Comment by bobbrow** [comment] 2016-04-07 17:35
I'm currently tracking this with issue #20.  Are you doing mixed D2D and D3D?  If you're just planning on using D2D (which is currently DX11 under the hood), you might consider checking out the [Win2D project](https://github.com/Microsoft/Win2D) which integrates very nicely with XAML.

**Comment by thecobblersfather** [comment] 2016-04-08 20:07
I had originally started the project using only C#, but Win2D seemed like a long workaround. It is just straight D2D, but my biggest problem so far is getting it work work on the UWP.
