### ISSUE TITLE
NuGet errors when building D3D12HelloWorld

### ISSUE THREAD

**Issue by Witek902** [microsoft/DirectX-Graphics-Samples#881] opened 2024-08-15 16:57 UTC
When building D3D12HelloWorld.sln solution I'm getting following errors:
`5>D:\DEV\EXTERNAL\DirectX-Graphics-Samples\Samples\Desktop\D3D12HelloWorld\src\HelloVAResourceInterop\D3D12HelloVAResourceInterop.vcxproj(156,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Direct3D.D3D12.1.613.1\build\native\Microsoft.Direct3D.D3D12.props.`

Microsoft Visual Studio Community 2022
Version 17.10.6
VisualStudio.17.Release/17.10.6+35201.131
Microsoft .NET Framework
Version 4.8.09037

**Comment by walbourn** [comment] 2024-08-15 21:54
If you are building from in the IDE, the NuGet restore should happen automatically. If you are building from the command-line, you need to use `nuget restore D3D12HelloWorld.sln` after downloading [nuget.exe](https://www.nuget.org/downloads).

**Comment by Witek902** [comment] 2024-08-17 10:29
I am trying to build from IDE

**Comment by oliverxyy** [comment] 2024-08-19 09:54
The D3D12 version specified in packages.config is different from .vcxproj file, fix either of them can work.
packages.config:
<packages>
  <package id="Microsoft.Direct3D.D3D12" version="1.614.1" targetFramework="native" />
</packages>

*.vcxproj
  <ImportGroup Label="ExtensionTargets">
    <Import Project="..\packages\Microsoft.Direct3D.D3D12.1.613.1\build\native\Microsoft.Direct3D.D3D12.targets" Condition="Exists('..\packages\Microsoft.Direct3D.D3D12.1.613.1\build\native\Microsoft.Direct3D.D3D12.targets')" />
  </ImportGroup>

**Comment by bub1ick** [comment] 2024-08-27 00:05
The issue stems from the commit regarding issue #879. It changed the required package version in lots of different `packges.config` files. Hope this helps.

**Comment by magi-guy** [comment] 2024-09-13 03:26
![image](https://github.com/user-attachments/assets/47cccd6d-a1de-45b6-be98-704d47489e32)
I'm putting this here because it fixed the problem for me, even though I have no idea why. Changing the version of the Agility SDK from 1.614.1 to 1.613.1 in _just_ the HelloWindow packages.config file fixed _every single build error_ for _every_ project. I do not know if this breaks anything else.

**Comment by walbourn** [comment] 2024-09-13 06:59
Yes, the problem is that the `D3D12HelloTriangle.vcxproj` and the `packages.config` are out of sync. Another fix is to open the .vcxproj in a text editor and change all the `1.613.1` references to `1.614.1 `

**Comment by Simran-B** [comment] 2024-09-22 17:11
Adjusting the .vcxproj files doesn't fix it on my end. It only changes the error from allegedly missing 1.613.1 to 1.614.1, but it is reported as installed. Running nuget restore didn't help either.

**Comment by stanard** [comment] 2024-09-22 18:12
I fixed it on my end by Search-And-Replace "1.613.1" with "1.614.1" in all vcxproj files. I'm staging a PR now.

**Comment by stanard** [comment] 2024-09-22 18:16
PR is merged:  https://github.com/microsoft/DirectX-Graphics-Samples/pull/886

Please reopen this issue if you still have problems.

**Closed by stanard** 2024-09-22 18:16 UTC
Labels: bug, samples
