### ISSUE TITLE
Examples won't run if first adapter doesn't support DX12

### ISSUE THREAD

**Issue by weltkante** [Microsoft/DirectX-Graphics-Samples#14] opened 2015-08-29 22:08 UTC
All examples pass nullptr as the first argument to D3D12CreateDevice. The implementation of D3D12CreateDevice is flawed in that it will pick the first adapter, regardless of whether it supports DX12 or not. This will result in device creation failing if the first adapter doesn't support DX12 but the second adapter does.

D3D12CreateDevice either needs to be fixed to pick the first working adapter (probably too late for that?), or the samples should be fixed to autodetect the first working adapter. Nobody should use the current flawed implementation of passing nullptr as first argument, because that means the application/game won't run on random machines which are unlucky enough to have their DX12 adapter in second position.

**Comment by amerkoleci** [comment] 2015-08-30 08:38
Happens to me too

**Comment by bobbrow** [comment] 2015-08-31 15:54
You are correct.  To give you some context, our original aim for the API samples was for each of them to highlight specific Direct3D APIs/features in the leanest way possible such that someone could take a look at the code file and follow it from beginning to end without too much "boilerplate" code getting in the way.  That is why you will also notice that other framework-type code paths are missing (such as handling WM_SIZE and DXGI_ERROR_DEVICE_REMOVED events).

That said, I will concede that we may have been too aggressive in pruning this from our setup code and should add it in because it will get in the way of some developers (such as yourself) getting started if they try to run the code.

**Comment by weltkante** [comment] 2015-09-01 08:25
I'm mostly worried about developers picking up that code and use D3D12CreateDevice passing nullptr, and if it works for them they never realize their app/game will fail on random machines.

Took me several evenings to figure out what caused it and I can imagine some devs with less resources won't spend that time after an app shipped and just say "get a DX12 machine".

Currently almost all samples on the net make the same mistake and it would be great to have samples with proper adapter selection code. Thanks in advance if we can get some :-)

**Comment by bobbrow** [comment] 2015-09-01 15:27
I sent out a change for review internally yesterday.  I plan to commit it today.

Be aware though, that this behavior is not a regression from previous versions of Direct3D.  Even 11 will pick your primary adapter by default.  The prevailing thought around the community is that most people use their most powerful (or recent) GPU as their primary adapter.  The majority of games do create the device by passing in nullptr for the adapter, so I would recommend you change your settings to avoid being broken in the future.

You should be able to set your DX12 GPU as your primary adapter by going to Display Settings and selecting "Make this my main display" while selecting the monitor that it is plugged in to.

**Comment by weltkante** [comment] 2015-09-01 16:24
Actually it is different, DX11 only reports a single adapter and works just fine. The AMD drivers are responsible to decide which chipset is running for which application and can even have different applications run on different chipsets. I don't really know what the hardware does, but from what I understand there is an onboard intel chipset which handles the normal operation (to save energy if you believe the marketing), and for high performance stuff like games it forwards everything to an AMD GPU. All games (and most Windows dialogs) only ever offer me one adapter, usually labeled by the intel chipset, only starting with DX12 I see two adapters offered by the API. Thats part of why it took me so long to figure out the problem.

Since both chipsets share the same display and everything I'm not sure I can configure which adapter is the first. Certainly not by selecting a monitor.

From what I gathered on the net this has been a trend for notebooks over the last several years. In fact when I bought the notebook I explicitely looked for one with a powerful enough GPU to play (and develop) DX11 games (at the time there was no DX12). They sold it listing only the AMD chipset so I was surprised it had a second chipset. From my research all newer notebooks I was interested in (at that time) used this dual chipset approach.

So since I can't seem to change adapter order, and DX12 is the first version which exposes both of this dual chipset, I believe its a different scenario to DX11 and the current behavior will be causing new problems for people.

**Comment by bobbrow** [comment] 2015-09-01 16:37
Ah, a hybrid laptop.  I thought you were talking about a desktop with two discrete GPUs.  DX12 allows developers to use both GPUs in parallel, so we certainly would want the integrated GPU to show up in the adapter list.  Let me ask around.  This reminds me of a driver bug we sent over to Intel recently.  We have seen a few problems with hybrids where the Intel adapter is trying to advertise itself as the primary.  Would you be willing to share a dxdiag with me?  I'll PM you if that's ok.

**Comment by weltkante** [comment] 2015-09-01 17:07
Sure, you can reach me via the mail on my profile.

**Comment by bobbrow** [comment] 2015-09-01 21:47
I just committed a change to develop that will allow the samples to enumerate adapters and choose the first one that supports DX12.  Note that the change is in the DXGI API which is why I asserted that you should get the same behavior regardless of the Direct3D API version you are using.

The caveat is that on hybrid systems, the AMD driver has the ability to hide the Intel adapter for known games/processes.  I don't expect SDK samples to make it onto that list, but AMD probably provides some settings that you can configure in the control panel to help it decide when to hide the Intel GPU or not.

You can test this theory by replacing the DX12 create device method with D3D11CreateDevice and pass in nullptr for the adapter.  d3d11device->QueryInterface for the IDXGIDevice and then get the adapter from it.  Compare that adapter with the first adapter that gets enumerated by EnumAdapters(which should be Intel) and see if they're the same.

**Comment by lijipeng787** [comment] 2015-09-02 16:01
Hi 
I just tried to enumerate adapters on my machine and used eg. D3D12CreateDevice(my_adapter_list...) to created device but an  error 0x887a0004 returned from this method, this laptop has two gpu with nvidia optimus (intel hd 4000 and nvidia gt 645m).
The  error  0x887a0004 still returned when  d3d12 device was created  by second device directly,but the second device (gt 645m) is support D3D_FEATURE_LEVEL_12_0.
I have checked my platform(win 10 pro ) and sdk version(10.0.10240.0) ,dx dig shows everything work normally

**Comment by bobbrow** [comment] 2015-09-02 16:14
Is the new explicit adapter enumeration code returning nullptr for you?  If so, then it sounds like the nVidia driver doesn't have support for that GPU.  It looks like that's a Kepler GPU, so I'm a bit surprised.  What's the driver version number?

**Comment by weltkante** [comment] 2015-09-02 17:16
@bobbrow Alright, I tested your suggestions. The adapter selection code works nicely.

DX11 reports the intel chipset as adapter (i.e. it's the same as the first adapter DXGI enumerates)

If I select "high performance" for the application in the AMD control center then DXGI no longer enumerates the intel chipset at all, DX12 works without passing an adapter, and DX11 reports the AMD adapter. The latter is suprising to me because in the past that was not how it worked, it always reported the intel chipset, and only the intel chipset, but you could clearly see the difference in performance if you changed the driver settings. Either driver bugs have been fixed since I last checked this, or the behavior changed with the Windows 10 update.

Anyways, I'm glad there are options to work around the problems caused by D3D12CreateDevice being called without an explicit adapter, so we don't have to rely on everyone implementing adapter selection code after all. Thanks for looking at the problem and explaining it :-)

**Comment by lijipeng787** [comment] 2015-09-03 03:59
Explicit adapter enumeration and attempt to create device in  D3D12CreateDevice(...) doesn't initialize the device(device is nullptr),and return code by this method show me this message : 
(0x887a004 Specified device interface or functionality is not supported on this system).

I have checked my nvidia driver version(355.60) and found some strange problems, In nvidia control panel, the DirectX runtime version and Directx API version is 12.0 but the DirectX feature level shows 11.0. The lastest driver version on nvidia website is 355.82. 

Is the driver problem？

**Comment by bobbrow** [comment] 2015-09-03 15:44
Yes, it's intentional that we don't initialize the device during enumeration.  We're just testing the driver to see if it's supported.  By the looks of things, the API is telling you that your GPU is not supported.

I believe that 355.82 is the latest driver out on Windows Update.  Please try installing that.  If it still doesn't work, I can send email out to nVidia to see if this GPU is supposed to be supported or not.

The difference between runtime/API version and feature level is one that has confused a lot of people.  DirectX 12 only requires "feature level" 11.  Note that we pass in D3D_FEATURE_LEVEL_11_0 to the CreateDevice function in the samples.  This is how we made DX12 available to the majority of the GPUs already out there.  Otherwise it would have needlessly required everyone to buy new graphics cards.  There are additional features available for GPUs that support feature level 12 and 12.1, but the current set of samples do not make use of those features.

**Comment by lijipeng787** [comment] 2015-09-04 09:17
Thanks. 
I didn't figured out the difference between D3D_FEATURE_LEVEL_11_0 and D3D_FEATURE_LEVEL_12_0 until you ponited out that we should pass in  D3D_FEATURE_LEVEL_11_0  to DirectX 12 CreateDevice function on a DirectX 11  conpatible device.
Kepler GPU do not support DirectX 12 completely,so i pass in D3D_FEATURE_LEVEL_12_0 to CreateDevice function result an error. Return code shows S_Ok when i pass in D3D_FEATURE_LEVEL_11_0 .

**Comment by bobbrow** [comment] 2015-09-04 16:28
Good to hear.  Merged the code into master and will close this issue now.

**Closed by bobbrow** 2015-09-04 16:28 UTC
Labels: bug
