### ISSUE TITLE
MiniEngine demo doesn't work on Intel Iris Pro 5200

### ISSUE THREAD

**Issue by TsinStudio** [Microsoft/DirectX-Graphics-Samples#16] opened 2015-08-30 05:49 UTC
![sc_20150830134738](https://cloud.githubusercontent.com/assets/5148744/9565892/d4b06da0-4f1d-11e5-854c-f361002491ae.png)

However, other samples are ok.

The graphics driver is the latest version.

**Comment by bobbrow** [comment] 2015-08-31 16:14
Thanks for reporting.  Is that a MacBook?  Those can be hard to find around here. ;)  I'll see if I can find a laptop with that chip in it and pass the bug on to Intel.

Just to confirm, you're only seeing that particle fountain and the rest of the scene renders black?  It doesn't crash?

**Comment by TsinStudio** [comment] 2015-09-01 00:16
It's MacBook Pro 15 Mid 2014. The demo doesn't crash, I can only find particles, fire and smoke in this demo.

**Comment by bobbrow** [comment] 2015-09-01 19:01
I was able to get a hold of a PC with an Iris Pro 5200 and saw the same problem that you did.  I can confirm that this is a driver bug.  I can't talk about schedules for driver updates, and I also can't promise that the next update will contain the fix.  But I can recommend that you monitor Windows Update to see when the next driver comes out.  If I happen to see it before you, I will update this issue.

**Comment by MauricioVives** [comment] 2015-09-02 06:18
I am seeing the same issue, also on a MacBook Pro.  Can you explain the nature of the driver bug so that we can avoid it in our own development?  Thanks.

**Comment by oscarbg** [comment] 2015-09-03 18:34
affects other Intel GPUs like Intel HD 530 in Skylake?

**Comment by alessiot89** [comment] 2015-09-11 19:50
Hi, driver version 15.40.7.4279 is available: https://downloadcenter.intel.com/product/81497/Intel-HD-Graphics-4400-for-4th-Generation-Intel-Core-Processors
I had the same issue with previous drivers running on an Intel HD 4400 (Surface Pro 3), now looks like it works fine with last drivers.

**Comment by MauricioVives** [comment] 2015-09-11 20:32
Also verified fixed with that driver on my MacBook Pro, Iris 5100.  Thanks alessiot89 for the notice!

**Comment by bobbrow** [comment] 2015-09-11 20:36
Thanks for the link Allessio!  That was the driver I tested earlier on the Iris Pro 5200 and was hoping it would be released.  It doesn't look like this driver is out on Windows Update yet (my Iris Pro I acquired doesn't see it), so if anyone wants to pick this up, you'll need to go to Intel's website for now.

**Comment by bobbrow** [comment] 2015-09-22 20:11
4281 is showing up on Windows Update today.

**Closed by bobbrow** 2015-09-22 20:11 UTC
