### ISSUE TITLE
VSGA crashes while inspecting pipeline state

### ISSUE THREAD

**Issue by sherief** [Microsoft/DirectX-Graphics-Samples#143] opened 2016-04-21 23:58 UTC
I have modified the HelloTriangle sample to read vertex positions from HLSL constants, and while rendering works as expected attempting to analyze the DrawInstanced() call in Visual Studio Graphics Analyzer causes the analyzer to crash. I attempted to submit feedback using Microsoft Connect and I get the following error message: "You are not authorized to submit the feedback for this connection.".

I have a diagsession that can help reproduce the issue, and I have the modified code that I can share. Where to go to get this fixed?

**Comment by bobbrow** [comment] 2016-04-22 00:00
If you send me the code I'll take a look and get a bug filed on the debugging tools.

**Comment by sherief** [comment] 2016-04-22 01:14
Awesome, I'll upload something later tonight or early tomorrow.

**Comment by sherief** [comment] 2016-04-22 20:32
Can you check the D3D12HelloTriangle at https://github.com/sherief/DirectX-Graphics-Samples ?

I run the sample and see a green triangle. I capture a frame, go into graphics analyzer, and try to inspect the pipeline state for the DrawInstanced() call in the command list and graphics analyzer crashes. Let me know if you have trouble reproducing or need more info.

**Comment by bobbrow** [comment] 2016-04-25 17:09
Can you share the output of the "System32 Info" section when you run ```dxcap -info``` in a CMD window?  I ran your project under the graphics debugger on the 10586 build of the tools and I don't get a crash.  The pipeline state doesn't seem to show up in the "Draw Calls" view of the event list in this version for some reason (I can't remember if this was the case in 10240 as well), but I can access it via the Object Table and it doesn't crash the analyzer when I open it.

**Comment by sherief** [comment] 2016-04-26 00:33
Attached.
[dxcap-info.txt](https://github.com/Microsoft/DirectX-Graphics-Samples/files/235676/dxcap-info.txt)

**Comment by bobbrow** [comment] 2016-04-26 20:08
Thanks.  Do you know if this is running on the Intel GPU or the NVidia GPU?  If you run on the other GPU or add ```/warp``` to the command line in the debugging properties in VS, and then capture/playback the scene again do you still reproduce the crash?  (I'm trying to rule out driver bugs at this point while I look for a laptop with similar specs)

**Comment by bobbrow** [comment] 2016-08-12 17:01
Let me know if you are still having issues with this.  I didn't hear back from you.

**Comment by sherief** [comment] 2016-08-13 21:35
Still an issue. Happens with the Intel HD 4000 GPU, NVIDIA 970M GPU, and WARP.

**Comment by sherief** [comment] 2016-08-19 07:23
Any updates? Have you been able to reproduce this issue?

**Comment by bobbrow** [comment] 2016-08-19 15:58
No, I have not had any success reproducing this.

**Comment by bobbrow** [comment] 2016-08-24 20:05
Maybe you can share your WARP vsglog that repros the issue?  Also, I'm not sure whether you've installed the Windows 10 Anniversary Update yet, but that might be a good thing to do.

**Comment by sherief** [comment] 2016-08-24 23:47
The former is easy, will do that once I have the bandwidth. I plan to run on Redstone (especially for the new D3D12 validation layer / root signature features) very soon, but I want to make sure I can push a stable build in the short term so this might take a week or two. Or four.

**Comment by bobbrow** [comment] 2016-10-03 16:13
Hi @sherief, just checking in to see if you have an update on this issue.

**Comment by sherief** [comment] 2016-10-16 13:20
I'm on vacation / away from my main machine right now. Will check this as soon as I get back.

**Comment by bobbrow** [comment] 2017-01-21 03:53
Feel free to give PIX for Windows a try.  I know you've filed other issues against VSGA, but the DirectX team is currently focusing its efforts on PIX for DX12 titles.  Unfortunately, that means that VSGA may not get a fix for this.

**Closed by bobbrow** 2017-01-21 03:53 UTC

**Comment by limdor** [comment] 2017-05-17 13:33
I'm experiencing the same problem with a DirectX 11.1 on Windows 8.1. It crash when inspecting the pipline state.
If I try to debug the crash the exception is this one:

System.ArgumentException was unhandled
Message: An unhandled exception of type 'System.ArgumentException' occurred in mscorlib.dll
Additional information: Requested value 'DXGI_FORMAT_DXGI_FORMAT_R32G32B32_FLOAT' was not found.

**Comment by bobbrow** [comment] 2017-05-18 16:52
It looks like DXGI_FORMAT was prepended to the format twice.  What version of VS are you using?  Can you send feedback via the feedback button in the top right corner of VS so the right team can take a look?  VS 2015 and 2017 should both have this.

![corner](https://cloud.githubusercontent.com/assets/12818240/26213929/87d89d4c-3baf-11e7-983f-7058c6e9710b.png)

**Comment by limdor** [comment] 2017-05-19 07:23
It is Visual Studio Community 2015 with Update 3 in a Windows 8.1.

I didn't create a new one because I see some in the search when reporting a problem but I cannot find the way to comment them adding additional information or to check if it is the same Visual Studio version. Do I create a new report anyway?

**Comment by weltkante** [comment] 2017-05-19 12:57
Its not very discoverable but there is https://developercommunity.visualstudio.com which lets you interact with posted issues in a web interface.
