### ISSUE TITLE
VSGD frame capture with Placed resource in an UPLOAD heap will not open

### ISSUE THREAD

**Issue by sherief** [Microsoft/DirectX-Graphics-Samples#161] opened 2016-06-01 23:25 UTC
Capturing a frame that renders a single triangle (Based on the HelloTriangle) sample crashes the graphics debugging tools with or without the debug SDK layer enabled. To reproduce, open the attached diag session in crashing frame.zip and double click the single captured frame. Output from dxcap -info also attached. Let me know if you need more information.

[crashing frame.zip](https://github.com/Microsoft/DirectX-Graphics-Samples/files/294538/crashing.frame.zip)

[dxcap_info.txt](https://github.com/Microsoft/DirectX-Graphics-Samples/files/294537/dxcap_info.txt)

**Comment by bobbrow** [comment] 2016-06-03 22:35
I can reproduce the crash and filed a bug for the graphics debugger team to take a look at.

**Comment by bobbrow** [comment] 2016-06-06 20:48
Hi @sherief, would you mind sharing your code to help expedite the investigation of this issue?

**Comment by sherief** [comment] 2016-06-07 06:48
I'll try to extract the pertinent parts - this was from a D3D12 engine bring-up so it links / references lots of engine code.

**Comment by sherief** [comment] 2016-06-20 02:52
Would a binary help? Source would need significant cleanup.

**Comment by bobbrow** [comment] 2016-06-20 20:52
Yes, that would also help.

**Comment by bobbrow** [comment] 2016-06-20 20:57
One other thing I should have asked earlier...  I noticed that you have both an Intel and an NVidia adapter.  Is your engine using both GPU's?  If that is the case, then I can let you know now that the graphics debugging tools don't support multi-GPU frame captures.

**Comment by sherief** [comment] 2016-06-20 23:41
We don't use multi-GPU currently. I'll attach a binary soon.

**Comment by sherief** [comment] 2016-08-09 07:03
*ahem* I suck at the concept of "soon", but here's a binary.
[d3d12-frame-capture-repro.zip](https://github.com/Microsoft/DirectX-Graphics-Samples/files/408353/d3d12-frame-capture-repro.zip)

**Comment by bobbrow** [comment] 2016-08-09 19:46
That binary didn't work for me.  It just popped up a cmd window and then exited.  d3d wasn't loaded.  I tried build 10586 and the Anniversary Update (14393).

But when I play back your capture it looks like the d3d is choking on a resource barrier.  I see an attempted transition from GENERIC_READ to COPY_DEST on an UPLOAD heap (resource).  Can you check and see if your code is attempting to make this transition?  UPLOAD heaps must stay in the GENERIC_READ state.

**Comment by sherief** [comment] 2016-08-10 11:33
Seems to have been an error on my part. Please try this binary and let me know if you're still running into API misuse issues: 
[d3d12_frame_capture_crash-08102016.zip](https://github.com/Microsoft/DirectX-Graphics-Samples/files/410929/d3d12_frame_capture_crash-08102016.zip)

**Comment by sherief** [comment] 2016-08-12 06:28
Please let me know if the binary works for you. I understand if you can't look at the bug soon, but I'd just like to make sure that you have all the info you asked for before I switch my attention to another project.

**Comment by bobbrow** [comment] 2016-08-12 16:47
This one works, but I was hoping you would respond to my question.  Are you attempting to transition a placed resource backed by an UPLOAD heap out of the GENERIC_READ state?  This is what appears to be causing the failure.  The UPLOAD heap I'm referring to is 0x8000000 bytes (~134MB).  If it's not you, then the debugger might be doing it erroneously, and I'll hand the bug back off to the debugger team to investigate.

**Comment by bobbrow** [comment] 2016-08-12 17:21
Nevermind.  I found the offending code in the graphics debugger.  It is inserting the transition barrier erroneously while reconstructing the buffer because it doesn't detect that the backing heap is an UPLOAD heap.  The debugger does this correctly for committed resources, but not placed resources.  I'll update the bug.

**Comment by sherief** [comment] 2016-08-13 21:23
Sorry for forgetting to answer the question - there are no code paths in this codebase that generate barriers (split or otherwise) that transition Upload Heap resources from GENERIC_READ to anything else.

I'm glad you found the cause. Let me know if you need anything else from my side.

**Comment by bobbrow** [comment] 2016-08-16 23:35
I've got the bug assigned to the appropriate developer.  If this issue is blocking you, the workaround is to use a Committed resource for your UPLOAD heap.

**Comment by bobbrow** [comment] 2017-01-21 03:51
This should be fixed in PIX for Windows.  https://blogs.msdn.microsoft.com/pix/2017/01/17/introducing-pix-on-windows-beta/

**Closed by bobbrow** 2017-01-21 03:51 UTC
